
import React, { useState } from 'react';
import { 
  Search, UserPlus, PieChart, Repeat, Settings, ArrowRight, 
  Bot, Target, Users, Sparkles, DollarSign, Zap, Briefcase, 
  Layers, Rocket, Info, ChevronRight, Loader2, Cpu
} from 'lucide-react';
import { GoogleGenAI, Type } from "@google/genai";

const FactoryStep = ({ stage, title, desc, icon: Icon, aiFeature }: any) => (
  <div className="group relative bg-slate-900 border border-slate-800 rounded-3xl p-8 hover:border-indigo-500/40 transition-all overflow-hidden shadow-lg hover:shadow-indigo-500/5">
    <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-600/5 rounded-full -mr-16 -mt-16 group-hover:bg-indigo-600/10 transition-colors" />
    <div className="relative z-10">
      <div className="flex items-center gap-3 mb-6">
        <div className="p-3 bg-slate-800 rounded-2xl text-indigo-400 group-hover:scale-110 transition-transform">
          <Icon size={28} />
        </div>
        <div>
          <span className="text-xs font-bold text-indigo-500 uppercase tracking-tighter">{stage}</span>
          <h3 className="text-xl font-bold">{title}</h3>
        </div>
      </div>
      <p className="text-slate-400 mb-6 leading-relaxed">
        {desc}
      </p>
      <div className="bg-slate-800/50 rounded-2xl p-4 border border-slate-700/50">
        <div className="flex items-center gap-2 text-xs font-bold text-slate-300 uppercase mb-2">
          <Bot size={14} className="text-cyan-400" />
          AI Enhancement 2026
        </div>
        <p className="text-sm text-indigo-300 italic">
          "{aiFeature}"
        </p>
      </div>
    </div>
  </div>
);

const RevenueFactoryView: React.FC = () => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [services, setServices] = useState([
    { id: 1, name: 'AI Customer Operations', pricing: '$2,500/mo', value: 'Reduces support costs by 70%' },
    { id: 2, name: 'Automated Outreach Factory', pricing: '$1,500/mo', value: '4x pipeline growth in 60 days' },
    { id: 3, name: 'AI Strategic Intelligence', pricing: '$5,000/mo', value: 'Real-time market pivot analysis' },
  ]);

  const generateNewService = async () => {
    setIsGenerating(true);
    try {
      // Create a new GoogleGenAI instance right before making an API call to ensure it always uses the most up-to-date API key
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: "Generate one unique, high-value AI service for businesses to sell in 2026. Focus on efficiency and revenue growth. Format: Name, Pricing (Monthly), Value Prop.",
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              name: { type: Type.STRING },
              pricing: { type: Type.STRING },
              value: { type: Type.STRING },
            }
          }
        }
      });
      const data = JSON.parse(response.text || '{}');
      setServices(prev => [{ ...data, id: Date.now() }, ...prev].slice(0, 5));
    } catch (e) {
      console.error(e);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-12 animate-in slide-in-from-bottom-4 duration-500 pb-20">
      <div className="text-center max-w-2xl mx-auto space-y-4">
        <h1 className="text-4xl lg:text-5xl font-black tracking-tight text-white">The Revenue Factory</h1>
        <p className="text-slate-400 text-lg">
          Transforming AI capabilities into a automated business engine for the 2026 economy.
        </p>
      </div>

      {/* CORE PIPELINE */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 relative">
        <div className="hidden md:block absolute top-1/2 left-1/3 w-1/3 h-px bg-slate-800 -translate-y-1/2" />
        <div className="hidden md:block absolute top-1/2 left-2/3 w-1/3 h-px bg-slate-800 -translate-y-1/2" />

        <FactoryStep 
          stage="Phase 01"
          title="Attraction Engine"
          desc="Predictive AI models identifying business pain-points before leads even search for solutions."
          icon={Search}
          aiFeature="Hyper-targeted outreach generated by native Gemini reasoning layers."
        />
        <FactoryStep 
          stage="Phase 02"
          title="Conversion Loop"
          desc="AI agents handling discovery, qualification, and objection handling with zero latency."
          icon={Repeat}
          aiFeature="Real-time sentiment analysis that adjusts the pitch during the interaction."
        />
        <FactoryStep 
          stage="Phase 03"
          title="Service Delivery"
          desc="Automated fulfillment using the AI Service Architect to ensure high-margin scalability."
          icon={Briefcase}
          aiFeature="Continuous autonomous refinement of client deliverables based on ROI data."
        />
      </div>

      {/* AI SERVICE ARCHITECT */}
      <div className="bg-slate-900 border border-slate-800 rounded-3xl overflow-hidden shadow-2xl">
        <div className="p-8 lg:p-12">
          <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-6 mb-10">
            <div>
              <h2 className="text-2xl font-bold flex items-center gap-3">
                <Cpu className="text-cyan-400" />
                AI Service Architect 2026
              </h2>
              <p className="text-slate-400 mt-1">Design and scale high-value services for B2B clients.</p>
            </div>
            <button 
              onClick={generateNewService}
              disabled={isGenerating}
              className="px-6 py-3 bg-indigo-600 hover:bg-indigo-700 disabled:bg-slate-800 text-white rounded-2xl font-bold transition-all flex items-center gap-2 shadow-lg shadow-indigo-600/20"
            >
              {isGenerating ? <Loader2 className="animate-spin" size={20} /> : <Sparkles size={20} />}
              Architect New Service
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {services.map((service) => (
              <div key={service.id} className="bg-slate-800/40 border border-slate-700/50 rounded-2xl p-6 hover:border-indigo-500/30 transition-all group">
                <div className="flex justify-between items-start mb-4">
                  <div className="p-2 rounded-lg bg-indigo-500/10 text-indigo-400">
                    <Rocket size={18} />
                  </div>
                  <span className="text-xs font-mono text-emerald-400 font-bold">{service.pricing}</span>
                </div>
                <h4 className="font-bold text-slate-100 group-hover:text-indigo-300 transition-colors">{service.name}</h4>
                <p className="text-xs text-slate-400 mt-2 leading-relaxed">
                  {service.value}
                </p>
                <div className="mt-6 flex items-center justify-between">
                   <div className="text-[10px] font-bold text-slate-500 uppercase">Operational</div>
                   <ChevronRight size={14} className="text-slate-600 group-hover:translate-x-1 transition-transform" />
                </div>
              </div>
            ))}
          </div>
        </div>
        
        {/* REVENUE PROJECTION */}
        <div className="bg-slate-800/30 border-t border-slate-800 p-8">
           <div className="flex flex-col md:flex-row items-center justify-between gap-8">
              <div className="flex items-center gap-4">
                 <div className="w-12 h-12 rounded-2xl bg-emerald-500/10 flex items-center justify-center text-emerald-400">
                    <DollarSign size={24} />
                 </div>
                 <div>
                    <div className="text-xs font-bold text-slate-500 uppercase tracking-widest">Target MRR (Q4 2026)</div>
                    <div className="text-2xl font-black">$45,000.00</div>
                 </div>
              </div>
              <div className="flex-1 max-w-md w-full">
                 <div className="flex justify-between text-[10px] font-bold text-slate-400 uppercase mb-2">
                    <span>Capacity Utilization</span>
                    <span>65%</span>
                 </div>
                 <div className="h-2 bg-slate-800 rounded-full overflow-hidden">
                    <div className="h-full w-[65%] bg-indigo-500 shadow-[0_0_10px_rgba(99,102,241,0.5)]" />
                 </div>
              </div>
              <div className="flex items-center gap-2 px-4 py-2 bg-slate-900 border border-slate-800 rounded-xl text-xs font-bold text-slate-400">
                 <Zap size={14} className="text-amber-400" />
                 High Efficiency Mode Active
              </div>
           </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-8 space-y-6">
          <h3 className="text-xl font-bold flex items-center gap-2">
            <Info size={20} className="text-indigo-400" />
            Strategic Protocol
          </h3>
          <p className="text-slate-400 text-sm leading-relaxed">
            The Revenue Factory is not just about leads; it's about the vertical integration of AI capabilities. In 2026, the dominant business model is "Result-as-a-Service," where you use the strategic core (Gemini 3 Pro) to fulfill complex operations for multiple clients simultaneously with near-zero variable cost.
          </p>
          <div className="grid grid-cols-2 gap-4">
             <div className="p-4 bg-slate-800/50 rounded-xl border border-slate-700/30">
                <div className="text-[10px] font-black text-indigo-400 uppercase mb-1">Scale Multiplier</div>
                <div className="text-lg font-bold">12.5x</div>
             </div>
             <div className="p-4 bg-slate-800/50 rounded-xl border border-slate-700/30">
                <div className="text-[10px] font-black text-cyan-400 uppercase mb-1">Human Overhead</div>
                <div className="text-lg font-bold">4.2%</div>
             </div>
          </div>
        </div>
        
        <div className="bg-indigo-600/5 border border-indigo-500/20 rounded-3xl p-8 flex flex-col justify-between">
           <div>
              <h3 className="text-xl font-bold text-indigo-100 mb-4">Factory Calibration Status</h3>
              <div className="space-y-4">
                 <div className="flex items-center gap-3 text-sm text-slate-300">
                    <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.5)]" />
                    Strategic Core: Gemini 3 Pro (Synched)
                 </div>
                 <div className="flex items-center gap-3 text-sm text-slate-300">
                    <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.5)]" />
                    Delivery Infrastructure: Autonomous Nodes (Active)
                 </div>
                 <div className="flex items-center gap-3 text-sm text-slate-300">
                    <div className="w-1.5 h-1.5 rounded-full bg-amber-500 shadow-[0_0_8px_rgba(245,158,11,0.5)]" />
                    Client Acquisition: Predictive Engine (Calibrating...)
                 </div>
              </div>
           </div>
           <button className="mt-8 w-full py-4 bg-white text-slate-900 rounded-2xl font-black text-sm uppercase tracking-widest hover:bg-slate-200 transition-colors shadow-xl">
              Initiate Scale Protocol
           </button>
        </div>
      </div>
    </div>
  );
};

export default RevenueFactoryView;